version: '3'
services:
  nexus:
    # Default credentials are: admin / admin123
    restart: always
    image: sonatype/nexus3:3.6.0
    container_name: dets_nexus
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./data:/nexus-data
    networks:
      - reverse_proxy

networks:
  reverse_proxy:
    external:
      name: reverse_proxy
