version: '2'
services:
  proxy:
    build: ./proxy
    ports:
      - "8080:80"
#    volumes:
#      - .:/code
#      - logvolume01:/var/log
#    links:
#      - gitlab
#      - redmine
#      - jenkins
#    redis:
#      image: redis
#    volumes:
#      logvolume01: {}



