version: '2'
services:
#  proxy:
#    build: ./proxy
#    ports:
#      - "80:80"
#    volumes:
#      - .:/code
#      - logvolume01:/var/log
#    links:
#      - gitlab
#      - redmine
#      - jenkins
#    redis:
#      image: redis
#    volumes:
#      logvolume01: {}

#####################################################
# GitLab
#####################################################

#  gitlab-mysql:
#    restart: always
#    image: sameersbn/mysql:latest
#    environment:
#      - DB_USER=gitlab
#      - DB_PASS=password
#      - DB_NAME=gitlabhq_production
##    volumes:
##      - /srv/docker/gitlab/postgresql:/var/lib/postgresql
#
#  gitlab:
##    restart: always
#    image: sameersbn/gitlab:8.6.3
#    links:
#      - gitlab-redis:redisio
#      - gitlab-mysql:mysql
#    environment:
#      - DB_TYPE=mysql
#      - DB_HOST=mysql
#      - DB_PORT=3306
#      - DB_USER=gitlab
#      - DB_PASS=password
#      - DB_NAME=gitlabhq_production
#
#      - REDIS_HOST=redisio
#      - REDIS_PORT=6379
#
#      - DEBUG=false
#      - TZ=Asia/Tokyo
#      - GITLAB_TIMEZONE=Tokyo
#
#      - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alphanumeric-string
#
##      - GITLAB_HOST=192.168.55.44
#      - GITLAB_PORT=8080
#      - GITLAB_SSH_PORT=10022
#      - GITLAB_RELATIVE_URL_ROOT=/gitlab
#
#      - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
#      - GITLAB_NOTIFY_PUSHER=false
#
#      - GITLAB_EMAIL=notifications@example.com
#      - GITLAB_EMAIL_REPLY_TO=noreply@example.com
#      - GITLAB_INCOMING_EMAIL_ADDRESS=reply@example.com
#
#      - GITLAB_BACKUP_SCHEDULE=daily
#      - GITLAB_BACKUP_TIME=01:00
#
#      - SMTP_ENABLED=false
#      - SMTP_DOMAIN=www.example.com
#      - SMTP_HOST=smtp.gmail.com
#      - SMTP_PORT=587
#      - SMTP_USER=mailer@example.com
#      - SMTP_PASS=password
#      - SMTP_STARTTLS=true
#      - SMTP_AUTHENTICATION=login
#
#      - IMAP_ENABLED=false
#      - IMAP_HOST=imap.gmail.com
#      - IMAP_PORT=993
#      - IMAP_USER=mailer@example.com
#      - IMAP_PASS=password
#      - IMAP_SSL=true
#      - IMAP_STARTTLS=false
#    ports:
#      - "10080:80"
##    volumes:
##      - /srv/docker/gitlab/gitlab:/home/git/data
#
#  gitlab-redis:
#    restart: always
#    image: sameersbn/redis:latest
##    volumes:
##      - /srv/docker/gitlab/redis:/var/lib/redis

#####################################################
# Redmine
#####################################################

#  redmine-postgresql:
#    image: sameersbn/postgresql:9.4-17
#    environment:
#      - DB_USER=redmine
#      - DB_PASS=password
#      - DB_NAME=redmine_production
##    volumes:
##      - /srv/docker/redmine/postgresql:/var/lib/postgresql
#
#  redmine:
#    image: sameersbn/redmine:3.2.1-2
#    links:
#      - redmine-postgresql:postgresql
#    environment:
#      - DB_TYPE=postgres
#      - DB_HOST=postgresql
#      - DB_PORT=5432
#      - DB_USER=redmine
#      - DB_PASS=password
#      - DB_NAME=redmine_production
#
#      - TZ=Asia/Tokyo
#
#      - REDMINE_PORT=10081
##       - REDMINE_HOST=192.168.55.44
#      - REDMINE_HTTPS=false
#      - REDMINE_RELATIVE_URL_ROOT=/redmine
#      - REDMINE_SECRET_TOKEN=
#
#      - REDMINE_SUDO_MODE_ENABLED=false
#      - REDMINE_SUDO_MODE_TIMEOUT=15
#
#      - REDMINE_CONCURRENT_UPLOADS=2
#
#      - REDMINE_BACKUP_SCHEDULE=
#      - REDMINE_BACKUP_EXPIRY=
#      - REDMINE_BACKUP_TIME=
#
#      - SMTP_ENABLED=false
#      - SMTP_METHOD=smtp
#      - SMTP_DOMAIN=www.example.com
#      - SMTP_HOST=smtp.gmail.com
#      - SMTP_PORT=587
#      - SMTP_USER=mailer@example.com
#      - SMTP_PASS=password
#      - SMTP_STARTTLS=true
#      - SMTP_AUTHENTICATION=:login
#
#      - IMAP_ENABLED=false
#      - IMAP_HOST=imap.gmail.com
#      - IMAP_PORT=993
#      - IMAP_USER=mailer@example.com
#      - IMAP_PASS=password
#      - IMAP_SSL=true
#      - IMAP_INTERVAL=30
#    ports:
#      - "10081:80"
##    volumes:
##      - /srv/docker/redmine/redmine:/home/redmine/data

#####################################################
# Jenkins
#####################################################

#  jenkins:
#    image: jenkins:1.642.2
#    environment:
##      - JENKINS_HOST=192.168.55.44
#      - JENKINS_OPTS=--prefix=/jenkins
##      - JENKINS_PORT=10082
#    ports:
#      - "10082:8080"

  rocketchat:
    image: rocketchat/rocket.chat:0.25.0
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost:3000/
      - MONGO_URL=mongodb://mongodb:27017/rocketchat
    links:
      - rocketchat-mongodb:mongodb
    ports:
      - 3000:3000
    volumes_from:
      - rocketchat-data

  rocketchat-mongodb:
    image: mongo:3.2.4
    ports:
      - 27017
    volumes_from:
      - rocketchat-data

  rocketchat-data:
    image: busybox:1.24.2
    volumes:
      # mongodb
      - /data/db
      - /data/configdb
      # rocketchat
      - /app/uploads
