version: '2'
services:
  openldap:
    image: dinkel/openldap:2.4.40
    environment:
      - SLAPD_PASSWORD=mysecretpassword
      - SLAPD_DOMAIN=ldap.example.org
      - SLAPD_ORGANIZATION="Example Inc."
      - SLAPD_FORCE_RECONFIGURE=false
    expose:
      - "389"
    volumes_from:
      - openldap-data
    networks:
      - backbone

  openldap-data:
    image: busybox:1.24.2
    volumes:
      - /etc/ldap
      - /var/lib/ldap

  phpldapadmin:
    image: dinkel/phpldapadmin:latest
    environment:
      - LDAP_SERVER_HOST=openldap
      - LDAP_SERVER_PORT=389
      - UNIQUE_ATTRS=mail,uid,uidNumbers
    ports:
      - 8080:80
    links:
      - openldap:openldap
    networks:
      - reverse_proxy
      - backbone

networks:
  reverse_proxy:
    external:
      name: reverse_proxy
  backbone:
    external:
      name: backbone
