FROM sameersbn/redmine:latest

## Gitmike ##
RUN git clone git://github.com/makotokw/redmine-theme-gitmike.git /home/redmine/redmine/public/themes/gitmike

## View-Customize ##
RUN git clone https://github.com/onozaty/redmine-view-customize.git /home/redmine/redmine/plugins/view_customize

