version: '3'
services:

#####################################################
# Elasticsearch + fluentd + Kibana
#####################################################
  elasticsearch:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.2
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    expose:
      - 9200
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - backbone

  fluent:
    restart: always
    build:
      context: ./fluent
    depends_on:
      - elasticsearch
    environment:
      - FLUENTD_CONF=fluent.conf
    volumes:
      - ./fluent/fluent.conf:/fluentd/etc/fluent.conf:ro
      - ../nginx/data/log:/home/fluent/log/nginx:ro # nginxのlog
    networks:
      - backbone

  kibana:
    restart: always
    image: docker.elastic.co/kibana/kibana:5.3.2
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - backbone

#  topbeat:
#    restart: always
#    build:
#      context: ./topbeat
#    depends_on:
#      - elasticsearch
#    pid: "host"
#    links:
#      - elasticsearch:elasticsearch
#    environment:
#      - HOST=elasticsearch
#      - PORT=9200
#      - CPU_PER_CORE=false
#      - INDEX=topbeat
#      - PROCS=.*
#      - PERIOD=10
#      - SHIPPER_NAME=
#      - SHIPPER_TAGS=

#####################################################
# network settings
#####################################################
networks:
  backbone:
    external:
      name: backbone
