version: "2"
services:

#####################################################
# Elasticsearch + fluentd + Kibana
#####################################################
  elasticsearch1:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    environment:
      - TZ=Asia/Tokyo
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.host=0.0.0.0
      # - transport.host=127.0.0.1
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    networks:
      - esnet

  elasticsearch2:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    environment:
      - TZ=Asia/Tokyo
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.host=0.0.0.0
      # - transport.host=127.0.0.1
      - bootstrap.memory_lock=true
      - "discovery.zen.ping.unicast.hosts=elasticsearch1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata2:/usr/share/elasticsearch/data
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - esnet

  fluent:
    restart: always
    build:
      context: ./fluent
    depends_on:
      - elasticsearch1
    links:
      - elasticsearch1:elasticsearch
    environment:
      - TZ=Asia/Tokyo
      - FLUENTD_CONF=fluent.conf
    volumes:
      - ./fluent/fluent.conf:/fluentd/etc/fluent.conf:ro
      - ../nginx/data/log:/home/fluent/log/nginx:ro # nginxのlog
    networks:
      - esnet

  kibana:
    restart: always
    image: docker.elastic.co/kibana/kibana:5.4.0
    depends_on:
      - elasticsearch1
    links:
      - elasticsearch1:elasticsearch
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - esnet

#  topbeat:
#    restart: always
#    build:
#      context: ./topbeat
#    depends_on:
#      - elasticsearch
#    pid: "host"
#    links:
#      - elasticsearch:elasticsearch
#    environment:
#      - HOST=elasticsearch
#      - PORT=9200
#      - CPU_PER_CORE=false
#      - INDEX=topbeat
#      - PROCS=.*
#      - PERIOD=10
#      - SHIPPER_NAME=
#      - SHIPPER_TAGS=

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

#####################################################
# network settings
#####################################################
networks:
  esnet:
