version: '2'
services:
#####################################################
# GitLab
#####################################################
  gitlab-postgresql:
    restart: always
    image: sameersbn/postgresql:9.4-22
    volumes:
      - ./data/gitlab/postgresql:/var/lib/postgresql:Z
    environment:
      - DB_USER=gitlab
      - DB_PASS=password
      - DB_NAME=gitlabhq_production
      - DB_EXTENSION=pg_trgm
    networks:
      - backbone

  gitlab:
    restart: always
    image: sameersbn/gitlab:8.9.3
    depends_on:
      - gitlab-postgresql
      - gitlab-redis
    links:
      - gitlab-redis:redisio
      - gitlab-postgresql:postgresql
    external_links:
      - ldap_openldap_1:openldap
    environment:
      - DB_ADAPTER=postgresql
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_USER=gitlab
      - DB_PASS=password
      - DB_NAME=gitlabhq_production

      - REDIS_HOST=redisio
      - REDIS_PORT=6379

      - DEBUG=false
      - TZ=Asia/Tokyo
      - GITLAB_TIMEZONE=Tokyo

      - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alphanumeric-string #change-it

      - GITLAB_HOST=localhost #change-it
      - GITLAB_PORT=80
      - GITLAB_SSH_PORT=10022 #change-it
      - GITLAB_RELATIVE_URL_ROOT=/portal/gitlab

      - GITLAB_ROOT_PASSWORD=5iveL!fe

      - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
      - GITLAB_NOTIFY_PUSHER=false

      - GITLAB_EMAIL=notifications@example.com #change-it
      - GITLAB_EMAIL_REPLY_TO=noreply@example.com #change-it
      - GITLAB_INCOMING_EMAIL_ADDRESS=reply@example.com #change-it

#      - GITLAB_BACKUP_DIR=/home/git/data/backups
#      - GITLAB_BACKUP_SCHEDULE=daily
#      - GITLAB_BACKUP_TIME=01:00

      - SMTP_ENABLED=false
      - SMTP_DOMAIN=www.example.com
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=mailer@example.com
      - SMTP_PASS=password
      - SMTP_STARTTLS=true
      - SMTP_AUTHENTICATION=login

      - IMAP_ENABLED=false
      - IMAP_HOST=imap.gmail.com
      - IMAP_PORT=993
      - IMAP_USER=mailer@example.com
      - IMAP_PASS=password
      - IMAP_SSL=true
      - IMAP_STARTTLS=false

      - LDAP_ENABLED=true
      - LDAP_LABEL=LDAP
      - LDAP_HOST=openldap
      - LDAP_PORT=389
      - LDAP_UID=cn
      - LDAP_METHOD=plain
      - LDAP_PASS=mysecretpassword #change-it
      - LDAP_BLOCK_AUTO_CREATED_USERS=false
      - LDAP_ACTIVE_DIRECTORY=false
      - LDAP_BASE=dc=example,dc=com #change-it
      - LDAP_USER_FILTER=
    ports:
      - "10022:22" #change-it
    volumes:
      - ./data/gitlab/gitlab:/home/git/data
    networks:
      - reverse_proxy
      - backbone

  gitlab-redis:
    restart: always
    image: sameersbn/redis:latest
    command:
      - --loglevel warning
    volumes:
      - ./data/gitlab/redis:/var/lib/redis:Z
    networks:
      - backbone

#  gitlab-kanban:
#    restart: always
#    image: leanlabs/kanban:1.6.0
#    environment:
#      # URL on which Leanlabs Kanban will be reachable
#      - KANBAN_SERVER_HOSTNAME=http://kanban.portal.local
#      # This string is used to generate user auth tokens
#      - KANBAN_SECURITY_SECRET=qwerty
#      # Your GitLab host URL
#      - KANBAN_GITLAB_URL=http://192.168.99.100/portal/gitlab
#      # Your GitLab OAuth client ID
#      - KANBAN_GITLAB_CLIENT=qwerty
#      # Your GitLab OAuth client secret key
#      - KANBAN_GITLAB_SECRET=qwerty
#      # Wheter to enable sign up with user API token
#      - KANBAN_ENABLE_SIGNUP=true
#      # Redis server address - IP:PORT
#      - KANBAN_REDIS_ADDR=redisio:6379
#    links:
#      - gitlab-kanban-redis:redisio
#    networks:
#      - reverse_proxy
#      - backbone
#    command: ./kanban server
#
#  gitlab-kanban-redis:
#    image: leanlabs/redis:1.0.0
#    networks:
#      - backbone



#####################################################
# Redmine
#####################################################
  redmine-postgresql:
    restart: always
    image: sameersbn/postgresql:9.4-22
    environment:
      - DB_USER=redmine
      - DB_PASS=password
      - DB_NAME=redmine_production
    volumes:
      - ./data/redmine/postgresql:/var/lib/postgresql
    networks:
      - backbone

  redmine:
    restart: always
    image: sameersbn/redmine:3.3.0
    depends_on:
      - redmine-postgresql
    links:
      - redmine-postgresql:postgresql
    external_links:
      - ldap_openldap_1:openldap
    environment:
      - DB_TYPE=postgres
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_USER=redmine
      - DB_PASS=password
      - DB_NAME=redmine_production

      - TZ=Asia/Tokyo

      - REDMINE_HOST=localhost #change-it
      - REDMINE_PORT=80
      - REDMINE_HTTPS=false
      - REDMINE_RELATIVE_URL_ROOT=/portal/redmine
      - REDMINE_SECRET_TOKEN=

      - REDMINE_SUDO_MODE_ENABLED=false
      - REDMINE_SUDO_MODE_TIMEOUT=15

      - REDMINE_CONCURRENT_UPLOADS=2

#      - REDMINE_BACKUPS_DIR=/home/redmine/data/backups
#      - REDMINE_BACKUP_SCHEDULE=daily
#      - REDMINE_BACKUP_EXPIRY=604800
#      - REDMINE_BACKUP_TIME=02:00

#      - SMTP_ENABLED=false
#      - SMTP_METHOD=smtp
#      - SMTP_DOMAIN=www.example.com
#      - SMTP_HOST=smtp.gmail.com
#      - SMTP_PORT=587
#      - SMTP_USER=mailer@example.com
#      - SMTP_PASS=password
#      - SMTP_STARTTLS=true
#      - SMTP_AUTHENTICATION=:login
#
#      - IMAP_ENABLED=false
#      - IMAP_HOST=imap.gmail.com
#      - IMAP_PORT=993
#      - IMAP_USER=mailer@example.com
#      - IMAP_PASS=password
#      - IMAP_SSL=true
#      - IMAP_INTERVAL=30
#    ports:
#      - "80:80"
    expose:
      - 80
    volumes:
      - ./data/redmine/redmine:/home/redmine/data
    networks:
      - reverse_proxy
      - backbone

#####################################################
# Jenkins
#####################################################
  jenkins:
    restart: always
    image: jenkins:2.3-alpine
    environment:
      - JENKINS_HOST=localhost #change-it
      - JENKINS_OPTS=--prefix=/portal/jenkins
      - JENKINS_PORT=8080
    external_links:
      - ldap_openldap_1:openldap
    expose:
      - 8080
    networks:
      - reverse_proxy
      - backbone

#####################################################
# Rocket.Chat
#####################################################
  rocketchat:
    restart: always
    image: rocketchat/rocket.chat:0.35.0
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost/portal/rocketchat
      - MONGO_URL=mongodb://mongodb:27017/rocketchat
      - ADMIN_PASS=admin
    links:
      - rocketchat-mongodb:mongodb
    external_links:
      - ldap_openldap_1:openldap
    volumes:
      - ./data/rocketchat/uploads:/app/uploads
    networks:
      - reverse_proxy
      - backbone

  rocketchat-mongodb:
    restart: always
    image: mongo:3.3.9
    volumes:
      - ./data/rocketchat/db:/data/db
      - ./data/rocketchat/configdb:/data/configdb
    networks:
      - backbone

#####################################################
# Elasticsearch + fluentd + Kibana + Topbeat
#####################################################
#  elasticsearch:
#    restart: always
#    image: elasticsearch:5.0.0-alpha1
#    volumes_from:
#      - log-analyze-data
#    ports:
#      - 9200:9200
#
#  fluent:
#    restart: always
#    build:
#      context: ./fluent
#    depends_on:
#      - elasticsearch
#    environment:
#      - FLUENTD_CONF=fluent.conf
#    volumes:
#      - ./data/fluent:/fluentd/etc:ro
#
#  kibana:
#    restart: always
#    image: kibana:5.0.0-alpha1
#    depends_on:
#      - elasticsearch
#    links:
#      - elasticsearch:elasticsearch
##    environment:
##      - ELASTICSEARCH_URL=http://elasticsearch:9200 # kibana.ymlでURLを指定するため、ここでは指定しない。docker-entrypoint.sh の実行で警告が出てしまうが...
#    volumes:
#      - ./data/kibana/config/kibana.yml:/opt/kibana/config/kibana.yml:ro
#    ports:
#      - 5601:5601
#
#  topbeat:
#    restart: always
#    build:
#      context: ./topbeat
#    depends_on:
#      - elasticsearch
#    pid: "host"
#    links:
#      - elasticsearch:elasticsearch
#    environment:
#      - HOST=elasticsearch
#      - PORT=9200
#      - CPU_PER_CORE=false
#      - INDEX=topbeat
#      - PROCS=.*
#      - PERIOD=10
#      - SHIPPER_NAME=
#      - SHIPPER_TAGS=
#
#  log-analyze-data:
#    image: busybox:1.24.2
#    volumes:
#      - /usr/share/elasticsearch/data

#####################################################
# ownCloud
#####################################################
  owncloud:
    restart: always
    image: cxpqwvtj/owncloud-ldap:9.0.1-apache
    environment:
      - OWNCLOUD_BASE_PATH=/portal/owncloud
    external_links:
      - ldap_openldap_1:openldap
    expose:
      - 80
    volumes:
      - ./data/owncloud:/var/www/html
    networks:
      - reverse_proxy

#####################################################
# alfresco
#####################################################
# TDOO:ownCloudをやめてalfrescoにする

#####################################################
# network settings
#####################################################
networks:
  reverse_proxy:
    external:
      name: reverse_proxy
  backbone:
    external:
      name: backbone
