version: '2'
services:
#####################################################
# GitLab
#####################################################
  gitlab-mysql:
    restart: always
    image: sameersbn/mysql:latest
    environment:
      - DB_USER=gitlab
      - DB_PASS=password
      - DB_NAME=gitlabhq_production
#    volumes:
#      - /srv/docker/gitlab/postgresql:/var/lib/postgresql
    networks:
      - backbone

  gitlab:
#    restart: always
    image: sameersbn/gitlab:8.6.3
    depends_on:
      - gitlab-mysql
      - gitlab-redis
    links:
      - gitlab-redis:redisio
      - gitlab-mysql:mysql
    external_links:
      - ldap_openldap_1:openldap
    environment:
      - DB_TYPE=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=gitlab
      - DB_PASS=password
      - DB_NAME=gitlabhq_production

      - REDIS_HOST=redisio
      - REDIS_PORT=6379

      - DEBUG=false
      - TZ=Asia/Tokyo
      - GITLAB_TIMEZONE=Tokyo

      - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alphanumeric-string

#      - GITLAB_HOST=192.168.55.44
      - GITLAB_PORT=8080
      - GITLAB_SSH_PORT=10022
      - GITLAB_RELATIVE_URL_ROOT=/portal/gitlab

      - GITLAB_ROOT_PASSWORD=5iveL!fe

      - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
      - GITLAB_NOTIFY_PUSHER=false

      - GITLAB_EMAIL=notifications@example.com
      - GITLAB_EMAIL_REPLY_TO=noreply@example.com
      - GITLAB_INCOMING_EMAIL_ADDRESS=reply@example.com

      - GITLAB_BACKUP_SCHEDULE=daily
      - GITLAB_BACKUP_TIME=01:00

      - SMTP_ENABLED=false
      - SMTP_DOMAIN=www.example.com
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=mailer@example.com
      - SMTP_PASS=password
      - SMTP_STARTTLS=true
      - SMTP_AUTHENTICATION=login

      - IMAP_ENABLED=false
      - IMAP_HOST=imap.gmail.com
      - IMAP_PORT=993
      - IMAP_USER=mailer@example.com
      - IMAP_PASS=password
      - IMAP_SSL=true
      - IMAP_STARTTLS=false

      - LDAP_ENABLED=true
      - LDAP_LABEL=LDAP
      - LDAP_HOST=openldap
      - LDAP_PORT=389
      - LDAP_UID=cn
      - LDAP_METHOD=plain
      - LDAP_PASS=mysecretpassword
      - LDAP_BLOCK_AUTO_CREATED_USERS=false
      - LDAP_ACTIVE_DIRECTORY=false
      - LDAP_BASE=dc=example,dc=com
      - LDAP_USER_FILTER=
#    ports:
#      - "10080:80"
#    volumes:
#      - /srv/docker/gitlab/gitlab:/home/git/data
    networks:
      - reverse_proxy
      - backbone

  gitlab-redis:
    restart: always
    image: sameersbn/redis:latest
#    volumes:
#      - /srv/docker/gitlab/redis:/var/lib/redis
    networks:
      - backbone

#####################################################
# Redmine
#####################################################
  redmine-postgresql:
    image: sameersbn/postgresql:9.4-17
    environment:
      - DB_USER=redmine
      - DB_PASS=password
      - DB_NAME=redmine_production
#    volumes:
#      - /srv/docker/redmine/postgresql:/var/lib/postgresql
    networks:
      - backbone

  redmine:
    image: sameersbn/redmine:3.2.1-2
    depends_on:
      - redmine-postgresql
    links:
      - redmine-postgresql:postgresql
    external_links:
      - ldap_openldap_1:openldap
    environment:
      - DB_TYPE=postgres
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_USER=redmine
      - DB_PASS=password
      - DB_NAME=redmine_production

      - TZ=Asia/Tokyo

      - REDMINE_PORT=80
#       - REDMINE_HOST=192.168.55.44
      - REDMINE_HTTPS=false
      - REDMINE_RELATIVE_URL_ROOT=/portal/redmine
      - REDMINE_SECRET_TOKEN=

      - REDMINE_SUDO_MODE_ENABLED=false
      - REDMINE_SUDO_MODE_TIMEOUT=15

      - REDMINE_CONCURRENT_UPLOADS=2

      - REDMINE_BACKUP_SCHEDULE=
      - REDMINE_BACKUP_EXPIRY=
      - REDMINE_BACKUP_TIME=

#      - SMTP_ENABLED=false
#      - SMTP_METHOD=smtp
#      - SMTP_DOMAIN=www.example.com
#      - SMTP_HOST=smtp.gmail.com
#      - SMTP_PORT=587
#      - SMTP_USER=mailer@example.com
#      - SMTP_PASS=password
#      - SMTP_STARTTLS=true
#      - SMTP_AUTHENTICATION=:login
#
#      - IMAP_ENABLED=false
#      - IMAP_HOST=imap.gmail.com
#      - IMAP_PORT=993
#      - IMAP_USER=mailer@example.com
#      - IMAP_PASS=password
#      - IMAP_SSL=true
#      - IMAP_INTERVAL=30
#    ports:
#      - "80:80"
    expose:
      - 80
#    volumes:
#      - /srv/docker/redmine/redmine:/home/redmine/data
    networks:
      - reverse_proxy
      - backbone

#####################################################
# Jenkins
#####################################################

  jenkins:
    image: jenkins:1.651.1-alpine
    environment:
#      - JENKINS_HOST=192.168.55.44
      - JENKINS_OPTS=--prefix=/portal/jenkins
#      - JENKINS_PORT=10082
    external_links:
      - ldap_openldap_1:openldap
    expose:
      - 8080
    networks:
      - reverse_proxy
      - backbone

#####################################################
# Rocket.Chat
#####################################################
  rocketchat:
    image: rocketchat/rocket.chat:0.28.0
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost/portal/rocketchat
      - MONGO_URL=mongodb://mongodb:27017/rocketchat
    links:
      - rocketchat-mongodb:mongodb
    external_links:
      - ldap_openldap_1:openldap
    volumes_from:
      - rocketchat-data
    networks:
      - reverse_proxy
      - backbone

  rocketchat-mongodb:
    image: mongo:3.2.4
    volumes_from:
      - rocketchat-data
    networks:
      - backbone

  rocketchat-data:
    image: busybox:1.24.2
    volumes:
      # mongodb
      - /data/db
      - /data/configdb
      # rocketchat
      - /app/uploads
    networks:
      - backbone

#####################################################
# Elasticsearch + fluentd + Kibana + Topbeat
#####################################################
#  elasticsearch:
#    image: elasticsearch:5.0.0-alpha1
#    volumes_from:
#      - log-analyze-data
#    ports:
#      - 9200:9200
#
#  fluent:
#    build:
#      context: ./fluent
#    depends_on:
#      - elasticsearch
#    environment:
#      - FLUENTD_CONF=fluent.conf
#    volumes:
#      - ./fluent:/fluentd/etc:ro
#
#  kibana:
#    image: kibana:5.0.0-alpha1
#    depends_on:
#      - elasticsearch
#    links:
#      - elasticsearch:elasticsearch
##    environment:
##      - ELASTICSEARCH_URL=http://elasticsearch:9200 # kibana.ymlでURLを指定するため、ここでは指定しない。docker-entrypoint.sh の実行で警告が出てしまうが...
#    volumes:
#      - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml:ro
#    ports:
#      - 5601:5601
#
#  topbeat:
#    build:
#      context: ./topbeat
#    depends_on:
#      - elasticsearch
#    pid: "host"
#    links:
#      - elasticsearch:elasticsearch
#    environment:
#      - HOST=elasticsearch
#      - PORT=9200
#      - CPU_PER_CORE=false
#      - INDEX=topbeat
#      - PROCS=.*
#      - PERIOD=10
#      - SHIPPER_NAME=
#      - SHIPPER_TAGS=
#
#  log-analyze-data:
#    image: busybox:1.24.2
#    volumes:
#      - /usr/share/elasticsearch/data

#####################################################
# ownCloud
#####################################################
  owncloud:
    image: cxpqwvtj/owncloud-ldap:9.0.1-apache
    environment:
      - OWNCLOUD_BASE_PATH=/portal/owncloud
    external_links:
      - ldap_openldap_1:openldap
    expose:
      - 80
    volumes_from:
      - owncloud-data
    networks:
      - reverse_proxy

  owncloud-data:
    image: busybox:1.24.2
    volumes:
      - /var/www/html
    networks:
      - backbone

networks:
  reverse_proxy:
    external:
      name: reverse_proxy
  backbone:
    external:
      name: backbone
