version: '2'
services:
  proxy:
    restart: always
    image: nginx:1.13.0
    environment:
      - TZ=Asia/Tokyo
    ports:
      - 80:80
      - 443:443
    external_links:
      - ldap_pocci-account-center_1:account.example.com
      - project_gitlab_1:gitlab.example.com
      - project_redmine_1:redmine.example.com
      - project_jenkins_1:jenkins.example.com
      - project_rocketchat_1:chat.example.com
      - project_owncloud_1:owncloud.example.com
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/config/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/html:/usr/share/nginx/html:ro
      - ./data/log:/var/log/nginx
      # サーバ証明書
      #- /usr/local/nginx/config/cert.pem:/usr/local/nginx/config/cert.pem
      #- /usr/local/nginx/config/cert.key:/usr/local/nginx/config/cert.key
      # クライアント証明書
      #- /usr/local/nginx/config/cacert.pem:/usr/local/nginx/config/cacert.pem
      #- /usr/local/nginx/config/crl.pem:/usr/local/nginx/config/crl.pem
    networks:
      - reverse_proxy

networks:
  reverse_proxy:
    external:
      name: reverse_proxy
