version: '2'
services:
  proxy:
    restart: always
    image: nginx:1.13.6
    container_name: dets_nginx
    environment:
      - TZ=Asia/Tokyo
    ports:
      - 80:80
      - 443:443
    external_links:
      - dets_account_center:account.example.com
      - dets_gitlab_app:gitlab.example.com
      - dets_redmine_app:redmine.example.com
      - dets_jenkins:jenkins.example.com
      - dets_rocketchat_app:chat.example.com
      - dets_owncloud:owncloud.example.com
      - dets_nexus:nexus.example.com
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/config/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/html:/usr/share/nginx/html:ro
      - ./data/log:/var/log/nginx
      # サーバ証明書
      #- /usr/local/nginx/config/cert.pem:/usr/local/nginx/config/cert.pem
      #- /usr/local/nginx/config/cert.key:/usr/local/nginx/config/cert.key
      # クライアント証明書
      #- /usr/local/nginx/config/cacert.pem:/usr/local/nginx/config/cacert.pem
      #- /usr/local/nginx/config/crl.pem:/usr/local/nginx/config/crl.pem
    networks:
      - reverse_proxy

networks:
  reverse_proxy:
    external:
      name: reverse_proxy
