version: '2'
services:
  proxy:
    image: nginx:1.9.15
    ports:
      - "80:80"
    links:
      - pocci-account-center:pocci-account-center
    external_links:
      - project_gitlab_1:portal-gitlab
      - project_redmine_1:portal-redmine
      - project_jenkins_1:portal-jenkins
      - project_rocketchat_1:portal-rocketchat
      - project_owncloud_1:portal-owncloud
#      - project_kibana_1:kibana
    volumes:
      - ./proxy/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/config/conf.d:/etc/nginx/conf.d:ro
      - ./proxy/html:/usr/share/nginx/html:ro
    networks:
      - reverse_proxy

  openldap:
    image: dinkel/openldap:2.4.40
    environment:
      - SLAPD_PASSWORD=mysecretpassword
      - SLAPD_DOMAIN=example.com
      - SLAPD_ORGANIZATION=Example Inc.
      - SLAPD_FORCE_RECONFIGURE=false
    expose:
      - "389"
    volumes_from:
      - openldap-data
    networks:
      - backbone

  openldap-data:
    image: busybox:1.24.2
    volumes:
      - /etc/ldap
      - /var/lib/ldap

  pocci-account-center:
    image: xpfriend/pocci-account-center:1.0.11
    environment:
      - LDAP_URL=ldap://openldap
      - LDAP_BASE_DN=dc=example,dc=com
      - USER_APP_PORT=9898
    expose:
      - 9898
    networks:
      - reverse_proxy
      - backbone

networks:
  reverse_proxy:
    external:
      name: reverse_proxy
  backbone:
    external:
      name: backbone
