version: '2'
services:
  proxy:
    image: nginx:1.9.15
    ports:
      - "80:80"
    external_links:
#      - openldap_openldap_1:openldap
      - project_gitlab_1:gitlab
      - project_redmine_1:redmine
#      - project_jenkins_1:jenkins
      - project_rocketchat_1:rocketchat
#      - project_kibana_1:kibana
    volumes:
      - ./proxy/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/config/conf.d:/etc/nginx/conf.d:ro
      - ./proxy/html:/usr/share/nginx/html:ro
    networks:
      - reverse_proxy

#  openldap:
#    image: dinkel/openldap:2.4.40
#    environment:
#      - SLAPD_PASSWORD=mysecretpassword
#      - SLAPD_DOMAIN=ldap.example.org
#      - SLAPD_ORGANIZATION="Example Inc."
#      - SLAPD_FORCE_RECONFIGURE=false
#    expose:
#      - "389"
#    volumes_from:
#      - openldap-data
#    networks:
#      - backbone
#
#  openldap-data:
#    image: busybox:1.24.2
#    volumes:
#      - /etc/ldap
#      - /var/lib/ldap
#
#  phpldapadmin:
#    image: dinkel/phpldapadmin:latest
#    environment:
#      - LDAP_SERVER_HOST=openldap
#      - LDAP_SERVER_PORT=389
#      - UNIQUE_ATTRS=mail,uid,uidNumbers
#    ports:
#      - 8080:80
#    links:
#      - openldap:openldap
#    networks:
#      - reverse_proxy
#      - backbone

networks:
  reverse_proxy:
    external:
      name: reverse_proxy
