version: '2'
services:
  proxy:
    image: nginx:1.9.15
    ports:
      - "80:80"
    external_links:
      - ldap_pocci-account-center_1:pocci-account-center
      - project_gitlab_1:portal-gitlab
      - project_redmine_1:portal-redmine
      - project_jenkins_1:portal-jenkins
      - project_rocketchat_1:portal-rocketchat
      - project_owncloud_1:portal-owncloud
#      - project_kibana_1:kibana
    volumes:
      - ./proxy/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/config/conf.d:/etc/nginx/conf.d:ro
      - ./proxy/html:/usr/share/nginx/html:ro
    networks:
      - reverse_proxy

networks:
  reverse_proxy:
    external:
      name: reverse_proxy
